### ISSUE TITLE
App stops with "Internal Server Error" every once in a while

### ISSUE THREAD

**Issue by larryqiann** [cedws/discord-delete#20]
The error message is FATA[0002] Error fetching messages for channel: Bad status code Internal Server Error 

This has happened with the older non-Go version as well, it looks like. I "fixed" it by wrapping it in a script that called it over and over again non stop, but that isn't an elegant solution.

Thanks

**Comment by cedws** [comment]
Yup, seen this happen occasionally too, but there's not much that can be done about it. It's Discord's API throwing a bad status. I didn't want the program to keep running if it received this status, because there's a risk that the program would be bombarding their API for no reason.

Your solution is okay to me. Make sure that you stop the script once all of your messages have been deleted though. Don't give them a reason to close your account.
