### ISSUE TITLE
Downgrade to API v9

### ISSUE THREAD

**Issue by tcrms** [cedws/discord-delete#52]
i don't see a reason to use [/api/v10/](https://discord.com/developers/docs/change-log#api-v10), as discord client (atleast canary/development) uses [/api/v9/](https://discord.com/developers/docs/change-log#api-v9), changing this may would lower the chances to get disabled as it would "spoof" also the endpoints you're sending and other related stuff

**Comment by cedws** [comment]
Not sure what you mean. Are you saying v9 will mean the client is likely to get banned on the basis that the Discord Client doesn't use v10 yet?

**Comment by cedws** [comment]
I think it's unlikely Discord's backend inspects requests like that. It might care about the "shape" and rate of requests but I doubt it's going to ban a client because it uses a newer API version than expected.

The spoofing implemented here isn't very clever, they could still easily detect it as a selfbot with TLS fingerprinting or by looking for specific headers. I just added it to try and blend in a bit more.
